version: 2


jobs:
    build:
        working_directory: ~/webdriver
        docker:
          - image: circleci/openjdk:8-browsers
        steps:
          - checkout
          - restore_cache:
              keys:
                - gradle-cache-{{ .Branch }}-{{ checksum "build.gradle" }}
          - save_cache:
              paths:
                - ~/.gradle
              key: gradle-cache-{{ .Branch }}-{{ checksum "build.gradle" }}
          - run:
              name: Run Tests
              command: gradle compileTestJava
          - run:
              name: Save test results
              command: mkdir -p ~/junit/ && find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
              when: always
          - store_test_results:
              path: ~/junit
          - store_artifacts:
              path: ~/junit
          - store_artifacts:
              path: build/reports
              destination: build/reports
          - store_artifacts:
              path: screenshots
              destination: screenshots
          - store_artifacts:
              path: logs/Test.log
              destination: logs/Test.log
workflows:
    version: 2
    branches:
        jobs:
            - build:
                filters:
                    branches:
                        only: master